# Generated by Django 3.2.7 on 2022-04-18 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbc',
            name='file',
            field=models.FileField(default=0, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cbc',
            name='image',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='tempFileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=0, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
